---
dt: 0.1
block_dt: 600
meas_dt:
  att: 0.1
  horizon_earth: 0.5
params:
  tau: [600.0, 600.0, 600.0, 600.0, 600.0, 600.0] # seconds
  q_a_psd_imu: 1.7361e-7 # 0.025**2 / 3600.0 -- versus 0.014 for the 370
  q_a_psd_dynamics: 1e-7 # From Liounis, Daniel, Christian (2013)
  q_w_psd: 5.4154e-10
  att_sigma_arcsec: [5.0, 5.0, 70.0] # star tracker standard deviation (z is star camera roll)
  horizon_max_phase_angle_deg: 150.0
  horizon_fov_deg: 30.0
  horizon_theta_max_deg: 70.0 # half angle of horizon to use
  horizon_fpa_size: 4096
  horizon_sigma_pix: 0.063
  horizon_n_max: 1000