---
dt: 0.1
order: [att, twoway_range, twoway_doppler]
block_dt: 600
meas_dt:
  att: 0.1
  twoway_range: 1.02
  twoway_doppler: 1.02
params:
  tau: [600.0, 600.0, 600.0, 600.0, 600.0, 600.0] # seconds
  q_a_psd_imu: 1.7361e-7 # 0.025**2 / 3600.0 -- versus 0.014 for the 370
  q_a_psd_dynamics: 1e-7 # From Liounis, Daniel, Christian (2013)
  q_w_psd: 5.4154e-10
